joy_teleop:
  ros__parameters:

    # 1. 주행 명령 (Ackermann 타입으로 변경)
    drive:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: drive
      deadman_buttons: [4] # L1 버튼
      axis_mappings:
        drive-speed:      # 전진/후진
          axis: 1
          scale: 2.0
          offset: 0.0
        drive-steering_angle:     # 조향
          axis: 3
          scale: 0.5
          offset: 0.0

    # 2. 비상 정지 버튼
    stop:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: drive
      deadman_buttons: [0] # A 버튼
      message_value:
        drive-speed:
          value: 0.0
        drive-steering_angle:
          value: 0.0
